name: OS Gasket Template Testing

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 7 * * 1-5" # 7 am UTC -> 12 am PST, 3 am EST

jobs:
  run-gasket-app-testing:
    uses: ./.github/workflows/_shared-gasket-testing.yaml
    with:
      app_matrix: >-
        [
          "os-template-nextjs-app",
          "os-template-nextjs-pages",
          "os-template-nextjs-express",
          "os-template-api-express",
          "os-template-api-fastify"
        ]
      env_vars: |
        GASKET_CI=1
        RUN_BUILD=1
        RUN_START=1
        RUN_LOCAL=1
        RUN_TEST=1
        RUN_DOCS=1
        EXIT_ON_ERROR=1
        # VERBOSE=1
        # OS_PREID=canary
        # INTERNAL_PREID=canary
      test_command: 'pnpm'
      workflow_name: 'gasket-template-testing'
      gasket_scope: 'OS'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
